language: c
dist: xenial
group: edge
virt: lxd
sudo: required

arch:
    - amd64
    - arm64
    - arm64-graviton2

addons:
    apt:
        packages:
            - automake
            - autoconf
            - codespell
            - libconfig-dev
            - libcunit1-dev
            - libssl-dev
            - libtool
            - pkg-config

compiler:
    - gcc
    - clang

script: ./scripts/travis.sh

jobs:
    include:
        - stage: test
          canfail: yes
          env: TEST=checkpatch
          compiler: gcc
          install:
                - true
          script:
                - echo ${TRAVIS_COMMIT_RANGE};
                - OFP_PATCHES=`echo ${TRAVIS_COMMIT_RANGE} | sed 's/\.//'`;
                - ./scripts/ci-checkpatches.sh ${OFP_PATCHES};
    allow_failures:
      - canfail: yes
